# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('thread', models.IntegerField()),
                ('reply_to', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('create_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('sent_timestamp', models.DateTimeField(default=None)),
                ('confirmed_timestamp', models.DateTimeField(default=None)),
                ('status', models.TextField(choices=[('', 'Just Created'), ('N', 'New and ready to be sent'), ('S', 'Sent but not confirmed'), ('V', 'Verified receipt'), ('C', 'Cancelled'), ('F', 'Failed')], default='', max_length=1)),
                ('reply_code', models.IntegerField()),
            ],
            options={
                'ordering': ['create_timestamp'],
                'get_latest_by': 'create_timestamp',
            },
            managers=[
                ('queue', django.db.models.manager.Manager()),
            ],
        ),
    ]
