# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.IntegerField(null=True),
        ),
    ]
