# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20161030_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.IntegerField(null=True),
        ),
    ]
