# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20161030_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='confirmed_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
